WADWebsite/Controllers/HomeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq; 
using System.Text.Json;
using WADWebsite.Models;

namespace WADAssignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;
        private IEnumerable<Festival> Festivals;
        const string SessionCart = "_Cart";

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }


        public IActionResult Index()
        {
            return View();
        }


        public IActionResult AllFestivals() //Used to show all data
        {

            List<Festival> Model = _context.Festivals.ToList();

            return View(Model);
        }


        public IActionResult OneFestival(short ID) //Used to show one festival when the festival image has been pressed
        {
            Festival model = _context.Festivals.Find(ID);

            return View(model);
        }


        public IActionResult Info()
        {
            return View();
        }

        public IActionResult SearchPage(string searchString)
        {
            var foundFestivals = _context.Festivals.Where(f => f.FestivalName.Contains(searchString));
            List<Festival> data = foundFestivals.ToList();
            return View(data);
        }

        public IActionResult SessionDemo()
        {
            if (HttpContext.Session.GetString("Name") == null)
            {
                ViewData["myName"] = "Not Set";
            }
            else
            {
                ViewData["myName"] = HttpContext.Session.GetString("Name"); ;
            }
            return View();
        }


        [HttpPost]
        public IActionResult FestivalDetails(IFormCollection form)
        {
            //Festival form = new Festival;

            int FestivalID = int.Parse(form["FestivalID"]);
            string FestivalName = form["FestivalName"].ToString();
            string TicketType = form["TicketType"].ToString();
            decimal TicketPrice = Decimal.Parse(form["TicketPrice"]);
            string FestivalImage = form["FestivalImage"].ToString();
            int OrderQuantity = 1;
            //int OrderQuantity = int.Parse(form["OrderQuantity"]);
            CartItem newOrder = new CartItem();
            newOrder.FestivalID = FestivalID;
            newOrder.FestivalName = FestivalName;
            newOrder.TicketType = TicketType;
            newOrder.TicketPrice = TicketPrice;
            newOrder.FestivalImage = FestivalImage;
            newOrder.OrderQuantity = OrderQuantity;
            newOrder.OrderDate = DateTime.Now;

            var CartList = new List<CartItem>();
            if (HttpContext.Session.GetString(SessionCart) != null)
            {
                string serialJSON = HttpContext.Session.GetString(SessionCart);
                CartList = JsonSerializer.Deserialize<List<CartItem>>(serialJSON);
                //
                var item = CartList.FirstOrDefault(o => o.FestivalID == FestivalID);
                if (item != null)
                {
                    item.OrderQuantity += OrderQuantity;
                }
                else
                {
                    CartList.Add(newOrder);
                }

            }
            else
            {
                CartList.Add(newOrder);
            }
            HttpContext.Session.SetString(SessionCart, JsonSerializer.Serialize(CartList));
            return RedirectToAction("ManageCart");

        }

        [HttpGet]
        public IActionResult ManageCart()

        {
            List<CartItem> cart = new List<CartItem>();
            if (HttpContext.Session.GetString(SessionCart) != null)
            {
                string serialJSON = HttpContext.Session.GetString(SessionCart);
                cart = JsonSerializer.Deserialize<List<CartItem>>(serialJSON);
            }
            if (TempData["msg"] != null)
            {
                ViewBag.msg = TempData["msg"].ToString();
            }
            return View(cart);

        }


        public IActionResult MinusQuantity(IFormCollection form)
        {
            int FestivalID = int.Parse(form["FestivalID"]);
            var CartList = new List<CartItem>();
            if (HttpContext.Session.GetString(SessionCart) != null)
            {
                string serialJSON = HttpContext.Session.GetString(SessionCart);
                CartList = JsonSerializer.Deserialize<List<CartItem>>(serialJSON);
                var item = CartList.FirstOrDefault(o => o.FestivalID == FestivalID);
                if (item != null && item.OrderQuantity > 1)
                {
                    item.OrderQuantity -= 1;
                }
                else if(item.OrderQuantity == 1)
                {
                    CartList.Remove(item);
                }

            }
            ManageCart();
            HttpContext.Session.SetString(SessionCart, JsonSerializer.Serialize(CartList));
            return RedirectToAction("ManageCart");
            
        }


        public IActionResult AddQuantity(IFormCollection form)
        {
            int FestivalID = int.Parse(form["FestivalID"]);
            var CartList = new List<CartItem>();
            if (HttpContext.Session.GetString(SessionCart) != null)
            {
                string serialJSON = HttpContext.Session.GetString(SessionCart);
                CartList = JsonSerializer.Deserialize<List<CartItem>>(serialJSON);
                var item = CartList.FirstOrDefault(o => o.FestivalID == FestivalID);
                if (item != null)
                {
                    item.OrderQuantity += 1;
                }

            }

            HttpContext.Session.SetString(SessionCart, JsonSerializer.Serialize(CartList));
            return RedirectToAction("ManageCart");
        }


        /*
        [HttpPost]
        public IActionResult RemoveCartItem(IFormCollection form)
        {
            int FestivalID = int.Parse(form["FestivalID"]);
            var CartList = new List<CartItem>();
            if (HttpContext.Session.GetString(SessionCart) != null)
            {
                string serialJSON = HttpContext.Session.GetString(SessionCart);
                CartList = JsonSerializer.Deserialize<List<CartItem>>(serialJSON);
                var item = CartList.FirstOrDefault(o => o.FestivalID == FestivalID);
                if (item != null)
                {
                    CartList.Remove(item);
                }
                        
            }

            HttpContext.Session.SetString(SessionCart, JsonSerializer.Serialize(CartList));
            TempData["msg"] = "Item Removed";
            return RedirectToAction("ManageCart");
        }
        */

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }





       
    
    }
}
 
    

WADWebsite/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using WADWebsite.Models;

namespace WADWebsite.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        const string SessionCart = "_Cart";

        public ShoppingCartViewComponent()
        {
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<CartItem> cart = new List<CartItem>();
            if (HttpContext.Session.GetString(SessionCart) != null)
            {
                string serialJSON = HttpContext.Session.GetString(SessionCart);
                cart = JsonSerializer.Deserialize<List<CartItem>>(serialJSON);
            }
            return View(cart);
        }
    }



}

WADWebsite/Views/Home/AllFestivals.cshtml
@{
    ViewData["Title"] = "Full Festival List";
    ViewData["PageHeading"] = "Full Festival List";
    
}


<section class="wrap">
    @foreach (var item in Model)
    {
        <div class="festivalThumb">
            <div>
                <a asp-controller="Home" asp-action="OneFestival" asp-route-ID=@item.FestivalID>
                    <img src="~/images/@item.FestivalImage" class ="cover" />
                </a>
                <h3>@item.FestivalName</h3>
                @if(@item.TicketType.Contains("Day"))
                {
                    <h4>@item.TicketType @item.StartDate.ToString("dd/MM/yy")</h4>
                }
                else
                {
                    <h4>@item.TicketType</h4>
                }

                    <h4>£@item.TicketPrice</h4>
            </div>
        </div>
    }
</section>

WADWebsite/Views/Home/FestivalDetails.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
    <form method="post">

        <input type="hidden" value="@Model.FestivalID" id="FestivalID" name="FestivalID" />

        <input type="hidden" value="@Model.FestivalName" id="FestivalName" name="FestivalName" />

        <input type="hidden" value="@Model.TicketType" id="TicketType" name="TicketType" />

        <input type="hidden" value="@Model.TicketPrice" id="TicketPrice" name="TicketPrice" />

        <div>

            <label for="OrderQuantity">Quantity</label>

            <input type="number" id="OrderQuantity" name="OrderQuantity" min="1" max="10" value="1" />

        </div>

        <div>

            <input type="submit" value="Add To Cart" class="cta" />

        </div>

    </form>

    <div class="shoppingCart">
        @await Component.InvokeAsync("ShoppingCart")
    </div>

WADWebsite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Are you a Raver?</h1>

    <h2>Well this is your kind of website</h2>
    <h3> We here at Regal Raverz believe that music makes the world go round</h3>
    <h4>Now join us by being the generation of ravers that the world rememebers for throughout the ages</h4>




</div>

WADWebsite/Views/Home/Info.cshtml
@{
    ViewData["Title"] = "Company Infomation";
}
<h1>@ViewData["Title"]</h1>

<h2>Welcome To Radical Raverz</h2>
<h3>This page gives you a little more information about the creator of this website and company</h3>
<p>Hi, My name's Ella, I am a Sheffield Hallam, Software Enginnering 2nd year student</p>
<p>For my final project in my Web App Development module I was asked to create a web page about something I'm passionate about</p>
<p>I chose to do a festival booker, I love eveything about festivals from the music to the camping element </p>
<p>This website shows different festivals and their choice of ticket types</p>

WADWebsite/Views/Home/ManageCart.cshtml
@{

    ViewData["Title"] = "Manage Cart";
    ViewData["PageHeading"] = "Manage Cart";
    decimal cartTotal = 0;

}
   
    <section class="wrap">



        
    @if (ViewBag.msg != null)
    {
        <p class="msg">@ViewBag.msg</p>
    }

    <div class="shopping-cart"> 
        <div class="cartItems">
            <div class="title">
                Shopping Bag
            </div>
            @if (Model.Count == 0)
            {
                <div class="emptyBag">
                    <p>Shopping Cart Empty.</p>
                </div>
            }
            else
            {


                @foreach (var item in Model)
                {

                    <div class="item">
                        <div class="buttons">
                            <span class="delete-btn"></span>
                        </div>

                        <div class="image">
                            <img src="~/images/@item.FestivalImage" alt="" />
                        </div>

                        <div class="description">
                            <span>@item.FestivalName</span>
                            <span>@item.TicketType</span>
                        </div>

                        <div class="quantity">

                            <form asp-controller="Home" asp-action="AddQuantity" method="post">
                                <input type="hidden" value="@item.FestivalID" name="FestivalID" />
                                <input type="submit" value="+" />
                            </form>
                            <input name="name" value="@item.OrderQuantity">
                            <form asp-controller="Home" asp-action="MinusQuantity" method="post">
                                <input type="hidden" value="@item.FestivalID" name="FestivalID" />
                                <input type="submit" value="-" />
                            </form>
                        </div>

                        <div class="total-price">£@((item.OrderQuantity * item.TicketPrice).ToString("0.00"))</div>
                    </div>

                 }
            }

        </div>
        <div class="basket-price">

            @foreach (var item in Model)
            {
                cartTotal = cartTotal + (item.OrderQuantity * item.TicketPrice);
            }


            <h3>Total Price: £@cartTotal.ToString("0.00")</h3>

        </div>
        
    </div>

     





            <!-- WORKING OLD CODDE

                       <button class="plus-btn" type="button" name="button">
                                   x
                                   <form>
                                   </form>

                               </button>



               <div>

                   @if (ViewBag.msg != null)
                   {

                       <p class="msg">@ViewBag.msg</p>

                   }

                   <table class="fullCart">

                       <tr>

                           <th>Name</th>

                           <th>Ticket Type</th>

                           <th>Price</th>

                           <th>Quantity</th>

                           <th>Cost</th>

                           <th></th>

                       </tr>

                       @foreach (var item in Model)

                       {

                           cartTotal += item.OrderQuantity * item.TicketPrice;

                   <tr>


                       <td>@item.FestivalName</td>

                       <td>@item.TicketType</td>

                       <td>£@(item.TicketPrice.ToString("0.00"))</td>

                       <td>@item.OrderQuantity</td>

                       <td>£@((item.OrderQuantity * item.TicketPrice).ToString("0.00"))</td>

                       <td>

                           <form method="post" asp-action="RemoveCartItem">

                               <input type="hidden" name="FestivalID" id="FestivalID" value="@item.FestivalID" />

                               <input type="submit" value="Remove" />

                           </form>

                       </td>

                   </tr>

                       }

                       <tr>

                           <td></td>

                           <td></td>

                           <td></td>

                           <td></td>

                           <td>£@cartTotal.ToString("0.00")</td>

                           <td></td>

                       </tr>

                   </table>

               </div>

               -->
        }
    </section>

WADWebsite/Views/Home/OneFestival.cshtml
@{
    //@Model WADWebsite.Models.Festival
    ViewData["Title"] = Model.FestivalName;


}
<style>
    .body{ 
        background-color:none;
    }
    .festContainer {
        background-image: url("/images/@Model.FestivalImage");
        background-size: 300px 300px;
        background-repeat: repeat
    }

</style>

<div class="festContainer">
    <div class="festivalInfo">
        <h1>Festival Details</h1>
        <div class="festName"><h2>@Model.FestivalName</h2></div>
        <div class="festTickType"><h3>@Model.TicketType</h3></div>
        @if (Model.CampingIncluded == true)
        {
            <div><h3>Camping included</h3></div>
        }
        else
        {
            <div><h3>Camping not included</h3></div>
        }
        <div class="festPrice"><h3>£@Model.TicketPrice</h3></div>
        @if (@Model.TicketType.Contains("Day"))
        {
            <div class="festDate"><h3>@Model.StartDate.ToString("dd/MM/yy")</h3></div>
        }
        else
        {
            <div class="festDate"><h3>@Model.StartDate.ToString("dd/MM/yy") to @Model.EndDate.ToString("dd/MM/yy")</h3></div>
        }

        @switch (Model.FestivalName)
        {
            case "Nass":
                <div><button class="glow-on-hover" onclick="window.location = 'https://www.nassfestival.com/lineup/';">Line Up</button></div>
                break;

            case "Parklife":
                <div><button class="glow-on-hover" onclick="window.location = 'https://parklife.uk.com/#lineup';">Line Up</button></div>
                break;

            case "Boomtown":
                <div><h5>Lineup not released</h5></div>
                break;

            case "Bassfest":
                <div><button class="glow-on-hover" onclick="window.location = 'https://www.electronic-festivals.com/event/bassfest-summer-festival#:~:text=The%20current%20lineup%20is%20not%20out%20yet.%20These,Boy%2C%20Swifta%20Beater%2C%20Notion%2C%20Ts7%2C%20Hedex%2C%20Splash%2C%20Conducta';">Line Up</button></div>
                break;

            case "Leedsfest":
                <div><button class="glow-on-hover" onclick="window.location = 'https://www.leedsfestival.com/lineup#poster';">Line Up</button></div>
                break;

            case "Reading fest":
                <div><button class="glow-on-hover" onclick="window.location = 'https://www.readingfestival.com/lineup#poster';">Line Up</button></div>
                break;

            case "Neighbourhood weekender":
                <div><button class="glow-on-hover" onclick="window.location = 'https://nbhdweekender.com/';">Line Up</button></div>
                break;

            case "Creamfields":
                <div><button class="glow-on-hover" onclick="window.location = 'https://creamfields.com/lineup';">Line Up</button></div>
                break;

            case "Shindig":
                <div><h5>Lineup not released</h5></div>
                break;

            case "Blue dot":
                <div><h5>Lineup not released</h5></div>
                break;

        }

        <form asp-controller="Home" asp-action="FestivalDetails" method="post">

            <input type="hidden" value="@Model.FestivalID" name="FestivalID" />
            <input type="hidden" value="@Model.FestivalName" name="FestivalName" />
            <input type="hidden" value="@Model.TicketType" name="TicketType" />
            <input type="hidden" value="@Model.TicketPrice" name="TicketPrice" />
            <input type="hidden" value="@Model.FestivalImage" name="FestivalImage" />
            <button type="submit" class="glow-on-hover">Add to Cart</button>

        </form>

    </div>

    @switch (Model.FestivalName)
    {
        case "Nass":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d637430.0020997052!2d-2.4649563991512337!3d51.385395821308315!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487224f11d035043%3A0xf288464399cdb6ee!2sThe%20Royal%20Bath%20%26%20West%20Showground!5e0!3m2!1sen!2snl!4v1623855954559!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

        case "Parklife":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d37947.273138415665!2d-2.281086943605166!3d53.52733287316332!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x83141b7c1fabbb4d!2sParklife%20Manchester!5e0!3m2!1sen!2snl!4v1623856356100!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

        case "Boomtown":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d320507.56805667525!2d-1.3011661441605622!3d51.127546694510386!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487413f62ef08e79%3A0x2c35a5c6c0eeb003!2sBoomtown%20Fair!5e0!3m2!1sen!2snl!4v1623856412154!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

        case "Bassfest":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9515.156607383038!2d-1.432573494178446!3d53.400711518816884!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487977a40def6bcb%3A0xafec53ee7b27e229!2sDon%20Valley%20Bowl!5e0!3m2!1sen!2snl!4v1623856461127!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

        case "Leedsfest":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d75313.4222629488!2d-1.4137304876702574!3d53.85096599639972!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x8cc467707b2fe52f!2sBramham%20Park!5e0!3m2!1sen!2snl!4v1623856587932!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

        case "Reading fest":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d9943.074434791015!2d-1.0002752423139875!3d51.46240470275564!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48769bac1a0a80f5%3A0x6840f8c838af189e!2sDrayton%20D%20A!5e0!3m2!1sen!2snl!4v1623856969720!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

        case "Neighbourhood weekender":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1189.883243455457!2d-2.5762377737824144!3d53.38322749497217!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487b021f9f9565a9%3A0xd93ee661aab20b7b!2sVictoria%20Park%2C%20Warrington%2C%20UK!5e0!3m2!1sen!2snl!4v1623857200848!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

        case "Creamfields":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2381.8065973536886!2d-2.628691548156107!3d53.34671817988085!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487afd9dd31799cd%3A0xe663de86de4a1848!2sCreamfields%20Festival!5e0!3m2!1sen!2snl!4v1623857252230!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

        case "Shindig":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d321188.92535434564!2d-3.2385553330707135!3d51.02929246772571!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487273ae9eb4ce4f%3A0xce4bd029d77d80f9!2sShindig%20Festival!5e0!3m2!1sen!2snl!4v1623857305176!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

        case "Blue dot":
            <iframe class="festivalMap" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d152769.08711288692!2d-2.434509159089362!3d53.25339564869691!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487a50fc0f5723ed%3A0xa1d78d08f23bd37c!2sJodrell%20Bank%20Discovery%20Centre!5e0!3m2!1sen!2snl!4v1623857407415!5m2!1sen!2snl" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            break;

    }
   
</div>


@*<div class="festivalLogo">
        <img src="~/images/@Model.FestivalImage" class="center" />
    </div>*@

WADWebsite/Views/Home/SearchPage.cshtml
@{
    ViewData["Title"] = "Search Results";
}

<h2>Search For Festival</h2>

<form asp-controller="Home" asp-action="SearchPage" method="get">
    <p>
        Festival Name: <input type="text" name="searchString" />
        <input type="submit" value="Filter" />
    </p>
</form>

@if (Model.Count == 0)
{
    <p>No Festivals found.</p>
}
else
{
    <p>@Model.Count Festivals found.</p>


    <section class="wrap">
        @foreach (var item in Model)
        {
            <div class="festivalThumb">
                <div>
                    <a asp-controller="Home" asp-action="OneFestival" asp-route-ID=@item.FestivalID>
                        <img src="~/images/@item.FestivalImage" height="200" width="200" />
                    </a>
                    <h3>@item.FestivalName</h3>
                    <h4>@item.TicketType</h4>
                    <h4>£@item.TicketPrice</h4>
                </div>
            </div>
        }
    </section>

}